### ISSUE TITLE
Is there any other languages provided?

### ISSUE THREAD

**Issue by yuuuuk0** [Dawid-Nowotny/FasterRCNN-object-detection#10]
I'm sorry that I can't understand the language of the application actually, is there any other languages povided, like English? Thanks.

**Comment by Dawid-Nowotny** [comment]
Hey there,
I've just updated the application so that you can now run it in English. Just use the --en flag when starting the app:
   ```bash
    python main.py --en
   ```

That should switch the interface to English for you.
Cheers.

**Comment by Dawid-Nowotny** [comment]
Hey there,
I've just updated the application so that you can now run it in English. Just use the --en flag when starting the app:
   ```bash
    python main.py --en
   ```

That should switch the interface to English for you.
Cheers.
